[build]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
cc = { path = "/scratch/iansseijelly/tacit-chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-gcc" }
cxx = { path = "/scratch/iansseijelly/tacit-chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-g++" }
ar = { path = "/scratch/iansseijelly/tacit-chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-ar" }
ranlib = { path = "/scratch/iansseijelly/tacit-chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-ranlib" }
linker = "/scratch/iansseijelly/tacit-chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-gcc" 
